### ISSUE TITLE
Intercept DPAD from the Key Mapper input method

### ISSUE THREAD

**Issue by sds100** [keymapperorg/KeyMapper#491]
https://developer.android.com/guide/topics/text/creating-input-method#HardwareKeyEvents

https://developer.android.com/training/game-controllers/controller-input

- input methods can consume KeyEvent and MotionEvents even without explicit focus
- override onKeyDown, onKeyUp and onGenericMotionEvent

**TODO**

- [ ] ~~see message in Discord server https://discord.com/channels/717499872219103263/717500452207591484/829428898097397791~~

**Suggested approach**
- [x] Show a bottom sheet if they don't detect any buttons after pressing record trigger. Suggest that they enable the key mapper keyboard to detect other buttons.
- [x] Show the popup if the activity detects a DPAD button being pressed while it is recording. Use a different title.
- [x] Make bottom sheet scrollable.
- [x] Send motion events from GUI keyboard
- [x] Do not record two trigger keys if the Key Mapper keyboard is used
- [x] Save with a trigger key whether it requires the input method for detecting. Have a KeyEventDetectionSource enum. By default it is accessibility service even if saved as null. Show this on the trigger key when configuring.
- [x] If the Key Mapper keyboard is selected then detect the key events
- [x] Advertise DPAD support in whats new.
- [x] update store description to say DPAD is supported
- [x] Check for minimum supported version of Key Mapper GUI Keyboard and show a dialog when opening Key Mapper and a notification if it needs updating. Do not allow them to not show it again. Clicking it opens Google Play
- [x] Set hold down option on by default when using a DPAD trigger
- [x] Consume motion events in mainactivity if they are a DPAD. Without this, recording dpad triggers with black xbox controller on my phone causes the DPAD to still move around the app.
- [x] Fix non-pro build type
- [x] Do not show DPAD error if DPAD button is detected by accessibility service
- [x] Do not record joysticks as DPAD buttons

**User support tasks**
- [x] message everyone in Discord server about DPAD support
- [ ] Remove the moderator filter for DPAD
- [x] Release new build of Key Mapper GUI Keyboard.

**Dpad bugs**
- [ ] ~~While moving head in minecraft with joystick, remapped DPAD button presses are ignored.~~ Not fixable because unless you consume *all* the motion events and reinject them with different data, Minecraft will still see that a DPAD button is pressed and react accordingly. One can not just consume the motion events where the dpad state _changes_.

**Testing strategy**
- [x] Try remapping DPAD triggers to movement key codes in minecraft
  - [x] With GUI Keyboard
  - [x] With Basic input method
- [x] Try old version of GUI keyboard with new app
- [x] Try new version of GUI keyboard with old app

**Comment by tiandongxv** [comment]
Hi, I have already use IME, still can’t create Trigger for DPAD, but I can create Action for DPAD, what am I wrong? Or can’t do such thing?

https://user-images.githubusercontent.com/11863878/113746962-79f59600-9739-11eb-97a6-faba2eef7124.mp4

**Comment by sds100** [comment]
Sorry for not clarifying. I haven't implemented this issue yet and you can create a "key" action for the DPAD because Key Mapper uses a different method to detect buttons when you're creating an action. This method only works as long as you're **in** Key Mapper .

**Comment by hxse** [comment]
![image](https://github.com/keymapperorg/KeyMapper/assets/22582226/f658a36b-5409-4beb-99a8-73972d220897)
With my gamepad, Up Down Left Right key, not work, Is progress going well?

**Comment by sds100** [comment]
This will be merged into issue #199

**Comment by sds100** [comment]
This will be implemented first in preparation for #199

**Comment by sds100** [comment]
implemented
