### ISSUE TITLE
Redo entire key map detection algorithm

### ISSUE THREAD

**Issue by sds100** [keymapperorg/KeyMapper#988]
**Developer TODO (don't remove)**
- [ ] keep old algorithm as a "legacy mode"
- [ ] update documentation
- [ ] Do this in **Rust**?? What is the cost of JNI when performing actions. Test this. If Expert Mode is enabled, can it run in the system bridge so that processing evdev events is lower latency?

## Requirements

Flow charts: [key-mapper-service.zip](https://github.com/keymapperorg/KeyMapper/files/8749332/key-mapper-service.zip)

- [ ] treat equivalent sequence triggers like double press triggers
- [ ] single press and long press triggers should still work even if you have a triple-press sequence triggers (in a similar way to having a short, long and double press on a trigger)
- [ ] if multiple modifier keys are used in a key map then they can be pressed in any order
- [ ] if fixing #940 make sure duplicate event trees aren't created if they already have another key map that has a trigger in the other order
- [ ] Remove double press triggers and the UI button just automatically adds a double sequence trigger.
- [ ] Button to quickly duplicate keys on trigger key list items.
- [ ] Button for custom delay lengths for each long press keys.
- [ ] #233 Interrupt feature to stop a repeating action when another key is pressed / added to the currently pressed key combo
- [ ] #360 Add chorded trigger capability a la chorded keyboards

**Comment by GL513** [comment]
What's happening??

**Comment by sds100** [comment]
Haha, it's currently awful, it's just bug fixes patched on top of bug fixes, and loads of current bugs are super hard to fix with the current state it is in.

**Comment by sds100** [comment]
Yes! I also have an extensive automated test suite that should ensure it behaves (mostly) correctly. I will keep the old one just for compatibility if people have issues.

**Comment by GL513** [comment]
Is there any chance that the daily builds can be posted in the discord too, or are the alphas already daily?

**Comment by sds100** [comment]
> Is there any chance that the daily builds can be posted in the discord too, or are the alphas already daily?

The alpha builds are automatically built whenever I push any code changes to the repository.

**Comment by sudomain** [comment]
I know development if the app has stopped, but I have a request related to the second point if someone (possibly myself) works on the key detection. I'd like to have an option in the form of a detection delay before the action(s) occurs. For example, I'd like to be able to have triple button press sequences (and even quadruple) that won't trigger my double button press sequences. I understand this will mean reduced speed in that the app will need more time to decide which keymap to execute, but will come with increased accuracy (by not triggering a double press when a triple press happens). Not everyone will want this so it would a good option to have.

**Comment by sds100** [comment]
Closing this because rewriting the algorithm is quite risky considering there is a lot of undefined behavior that millions of users have potentially relied on. The code is not my best and is more of a patchwork of edge cases but there is no way to define and test every scenario since the options are near infinite.

**Comment by sds100** [comment]
It would be huge for the app to redo how triggers are done... and live up to its promise of infinite flexibility.

**Comment by githubsterer** [comment]
Amen.

**Comment by eMPee584** [comment]
Ok now as it seems concepts of a plan for this are in place 🥲 💭 🚀 
.. where's our shut-up-and-take-my-money bounty link 😅

**Comment by jambl3r** [comment]
As much as I would love this to be done soon, I'd say it's extremely unlikely to happen this year.
I could see it happening next year depending on how the [new app](https://github.com/keymapperorg/KeyMapper/issues/1744) goes.

**Comment by sds100** [comment]
I'm starting to build a concept of a plan for this ;) One can dream... 8 years later. I will try to do it before Key Mapper's 10 year anniversary 😂
